import { players } from "./players";
import { teams } from "./teams";

export const data = [
  {
    team: teams.TSM,
    year: "2013",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.Dyrus,
      JG: players.JG.TheOddOne,
      MID: players.MID.Reginald,
      BOT: players.BOT.Chaox,
      SPT: players.SPT.Xpecial,
    },
  },
  {
    team: teams.TSM,
    year: "2014",
    split: "summer",
    region: "NA",
    players: {
      TOP: players.TOP.Dyrus,
      JG: players.JG.Amazing,
      MID: players.MID.Bjergsen,
      BOT: players.BOT.WildTurtle,
      SPT: players.SPT.Lustboy,
    },
  },
  {
    team: teams.TSM,
    year: "2016",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.Hauntzer,
      JG: players.JG.Svenskeren,
      MID: players.MID.Bjergsen,
      BOT: players.BOT.Doublelift,
      SPT: players.SPT.YellOwStaR,
    },
  },
  {
    team: teams.TSM,
    year: "2020",
    split: "summer",
    region: "NA",
    players: {
      TOP: players.TOP.BrokenBlade,
      JG: players.JG.Spica,
      MID: players.MID.Bjergsen,
      BOT: players.BOT.Doublelift,
      SPT: players.SPT.Treatz,
    },
  },
  {
    team: teams.TSM,
    year: "2021",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.Huni,
      JG: players.JG.Spica,
      MID: players.MID.PowerOfEvil,
      BOT: players.BOT.Lost,
      SPT: players.SPT.SwordArt,
    },
  },
  {
    team: teams.DIG,
    year: "2015",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.Gamsu,
      JG: players.JG.Crumbz,
      MID: players.MID.Shiphtur,
      BOT: players.BOT.CoreJJ,
      SPT: players.SPT.KiWiKiD,
    }
  },
  {
    team: teams.TL,
    year: "2019",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.Impact,
      JG: players.JG.Xmithie,
      MID: players.MID.Jensen,
      BOT: players.BOT.Doublelift,
      SPT: players.SPT.CoreJJ,
    },
  },
  {
    team: teams.TL,
    year: "2021",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.Alphari,
      JG: players.JG.Santorin,
      MID: players.MID.Jensen,
      BOT: players.BOT.Tactical,
      SPT: players.SPT.CoreJJ,
    },
  },
  {
    team: teams.C9,
    year: "2018",
    split: "summer",
    region: "NA",
    players: {
      TOP: players.TOP.Licorice,
      JG: players.JG.Svenskeren,
      MID: players.MID.Jensen,
      BOT: players.BOT.Sneaky,
      SPT: players.SPT.Zeyzal,
    },
  },
  {
    team: teams.C9,
    year: "2021",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.Fudge,
      JG: players.JG.Blaber,
      MID: players.MID.Perkz,
      BOT: players.BOT.Zven,
      SPT: players.SPT.Vulcan,
    },
  },
  {
    team: teams.FLY,
    year: "2020",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.Solo,
      JG: players.JG.Santorin,
      MID: players.MID.PowerOfEvil,
      BOT: players.BOT.WildTurtle,
      SPT: players.SPT.IgNar,
    },
  },
  {
    team: teams.FLY,
    year: "2021",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.Licorice,
      JG: players.JG.Josedeodo,
      MID: players.MID.Palafox,
      BOT: players.BOT.Johnsun,
      SPT: players.SPT.Dreams,
    },
  },
  {
    team: teams.REN,
    year: "2016",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.RFLegendary,
      JG: players.JG.Crumbz,
      MID: players.MID.AlexIch,
      BOT: players.BOT.Freeze,
      SPT: players.SPT.Remilia,
    },
  },
  {
    team: teams.NV,
    year: "2017",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.Seraph,
      JG: players.JG.Lira,
      MID: players.MID.Nisqy,
      BOT: players.BOT.Apollo,
      SPT: players.SPT.Hakuho,
    },
  },
  {
    team: teams.IMT,
    year: "2017",
    split: "summer",
    region: "NA",
    players: {
      TOP: players.TOP.Flame,
      JG: players.JG.Xmithie,
      MID: players.MID.Pobelter,
      BOT: players.BOT.CodySun,
      SPT: players.SPT.Olleh,
    },
  },
  {
    team: teams.IMT,
    year: "2020",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.sOAZ,
      JG: players.JG.Xmithie,
      MID: players.MID.Eika,
      BOT: players.BOT.Apollo,
      SPT: players.SPT.Hakuho,
    },
  },
  {
    team: teams['100'],
    year: "2019",
    split: "summer",
    region: "NA",
    players: {
      TOP: players.TOP.FakeGod,
      JG: players.JG.Amazing,
      MID: players.MID.Ryu,
      BOT: players.BOT.Bang,
      SPT: players.SPT.aphromoo,
    },
  },
  {
    team: teams['100'],
    year: "2021",
    split: "spring",
    region: "NA",
    players: {
      TOP: players.TOP.SSumday,
      JG: players.JG.Closer,
      MID: players.MID.Ry0ma,
      BOT: players.BOT.FBI,
      SPT: players.SPT.Huhi,
    },
  },
  {
    team: teams.CLG,
    year: "2014",
    split: "summer",
    region: "NA",
    players: {
      TOP: players.TOP.Seraph,
      JG: players.JG.Dexter,
      MID: players.MID.Link,
      BOT: players.BOT.Doublelift,
      SPT: players.SPT.aphromoo,
    },
  },
  {
    team: teams.FNC,
    year: "2013",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.sOAZ,
      JG: players.JG.Cyanide,
      MID: players.MID.XPeke,
      BOT: players.BOT.YellOwStaR,
      SPT: players.SPT.NRated,
    },
  },
  {
    team: teams.FNC,
    year: "2015",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Huni,
      JG: players.JG.Reignover,
      MID: players.MID.Febiven,
      BOT: players.BOT.Steelback,
      SPT: players.SPT.YellOwStaR,
    },
  },
  {
    team: teams.FNC,
    year: "2018",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Bwipo,
      JG: players.JG.Broxah,
      MID: players.MID.Caps,
      BOT: players.BOT.Rekkles,
      SPT: players.SPT.Hylissang,
    },
  },
  {
    team: teams.FNC,
    year: "2020",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Bwipo,
      JG: players.JG.Selfmade,
      MID: players.MID.Nemesis,
      BOT: players.BOT.Rekkles,
      SPT: players.SPT.Hylissang,
    },
  },
  {
    team: teams.G2,
    year: "2016",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Kikis,
      JG: players.JG.Trick,
      MID: players.MID.Perkz,
      BOT: players.BOT.Emperor,
      SPT: players.SPT.Hybrid,
    },
  },
  {
    team: teams.G2,
    year: "2018",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Wunder,
      JG: players.JG.Jankos,
      MID: players.MID.Perkz,
      BOT: players.BOT.Hjarnan,
      SPT: players.SPT.Wadid,
    },
  },
  {
    team: teams.G2,
    year: "2019",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Wunder,
      JG: players.JG.Jankos,
      MID: players.MID.Caps,
      BOT: players.BOT.Perkz,
      SPT: players.SPT.Mikyx,
    },
  },
  {
    team: teams.DB,
    year: "2013",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Spontexx,
      JG: players.JG.Malunoo,
      MID: players.MID.Shushei,
      BOT: players.BOT.HosaN,
      SPT: players.SPT.Muvert,
    },
  },
  {
    team: teams.SK,
    year: "2013",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Kev1n,
      JG: players.JG.HyrqBot,
      MID: players.MID.Ocelote,
      BOT: players.BOT.CandyPanda,
      SPT: players.SPT.Nyph,
    },
  },
  {
    team: teams.SK,
    year: "2015",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.fredy122,
      JG: players.JG.Svenskeren,
      MID: players.MID.Fox,
      BOT: players.BOT.FORG1VEN,
      SPT: players.SPT.NRated,
    },
  },
  {
    team: teams.GMB,
    year: "2013",
    split: "summer",
    region: "EU",
    players: {
      TOP: players.TOP.Darien,
      JG: players.JG.Diamondprox,
      MID: players.MID.AlexIch,
      BOT: players.BOT.Genja,
      SPT: players.SPT.Voidle,
    },
  },
  {
    team: teams.GMB,
    year: "2015",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Cabochard,
      JG: players.JG.Diamondprox,
      MID: players.MID.NiQ,
      BOT: players.BOT.P1noy,
      SPT: players.SPT.Edward,
    },
  },
  {
    team: teams.SHC,
    year: "2014",
    split: "summer",
    region: "EU",
    players: {
      TOP: players.TOP.Mimer,
      JG: players.JG.Impaler,
      MID: players.MID.Selfie,
      BOT: players.BOT.MrRalleZ,
      SPT: players.SPT.kaSing,
    },
  },
  {
    team: teams.H2K,
    year: "2016",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Odoamne,
      JG: players.JG.Jankos,
      MID: players.MID.Ryu,
      BOT: players.BOT.FORG1VEN,
      SPT: players.SPT.Vander,
    },
  },
  {
    team: teams.UOL,
    year: "2015",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Vizicsasci,
      JG: players.JG.Kikis,
      MID: players.MID.PowerOfEvil,
      BOT: players.BOT.Vardags,
      SPT: players.SPT.Hylissang,
    },
  },
  {
    team: teams.OG,
    year: "2015",
    split: "summer",
    region: "EU",
    players: {
      TOP: players.TOP.sOAZ,
      JG: players.JG.Amazing,
      MID: players.MID.XPeke,
      BOT: players.BOT.Zven,
      SPT: players.SPT.Mithy,
    },
  },
  {
    team: teams.OG,
    year: "2020",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Alphari,
      JG: players.JG.Xerxe,
      MID: players.MID.Nukeduck,
      BOT: players.BOT.Upset,
      SPT: players.SPT.Destiny,
    },
  },
  {
    team: teams.MSF,
    year: "2017",
    split: "summer",
    region: "EU",
    players: {
      TOP: players.TOP.Alphari,
      JG: players.JG.Maxlore,
      MID: players.MID.PowerOfEvil,
      BOT: players.BOT.HansSama,
      SPT: players.SPT.IgNar,
    },
  },
  {
    team: teams.S04,
    year: "2018",
    split: "summer",
    region: "EU",
    players: {
      TOP: players.TOP.Vizicsasci,
      JG: players.JG.Amazing,
      MID: players.MID.Nukeduck,
      BOT: players.BOT.Upset,
      SPT: players.SPT.Vander,
    },
  },
  {
    team: teams.S04,
    year: "2020",
    split: "summer",
    region: "EU",
    players: {
      TOP: players.TOP.Odoamne,
      JG: players.JG.Gilius,
      MID: players.MID.Abbedagge,
      BOT: players.BOT.Neon,
      SPT: players.SPT.Dreams,
    },
  },
  {
    team: teams.ROC,
    year: "2015",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Overpow,
      JG: players.JG.Jankos,
      MID: players.MID.Nukeduck,
      BOT: players.BOT.Woolite,
      SPT: players.SPT.Vander,
    },
  },
  {
    team: teams.RGE,
    year: "2021",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Odoamne,
      JG: players.JG.Inspired,
      MID: players.MID.Larssen,
      BOT: players.BOT.HansSama,
      SPT: players.SPT.Trymbi,
    },
  },
  {
    team: teams.MAD,
    year: "2021",
    split: "spring",
    region: "EU",
    players: {
      TOP: players.TOP.Armut,
      JG: players.JG.Elyoya,
      MID: players.MID.Humanoid,
      BOT: players.BOT.Carzzy,
      SPT: players.SPT.Kaiser,
    },
  },
  {
    team: teams.VIT,
    year: "2018",
    split: "summer",
    region: "EU",
    players: {
      TOP: players.TOP.Cabochard,
      JG: players.JG.Kikis,
      MID: players.MID.Jiizuke,
      BOT: players.BOT.Attila,
      SPT: players.SPT.Jactroll,
    },
  },
];
